import { ArrowRight, ExternalLink, FileText, HeartHandshake, Mail, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { SiteFooter, SiteHeader } from "@/components/SiteChrome";

type InfoPageProps = { eyebrow: string; title: string; lead: string; children: React.ReactNode };

function InfoPage({ eyebrow, title, lead, children }: InfoPageProps) {
  return <div className="min-h-screen bg-[#f6f4ef] text-[#14212b]"><SiteHeader /><main className="container py-12 md:py-18"><section className="mx-auto max-w-4xl"><p className="text-xs font-bold tracking-[0.15em] text-[#a25e2a] uppercase">{eyebrow}</p><h1 className="mt-4 max-w-3xl font-display text-5xl font-semibold leading-[0.98] tracking-[-0.055em] md:text-6xl">{title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#637078]">{lead}</p><div className="mt-10 space-y-8">{children}</div></section></main><SiteFooter /></div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-[26px] border border-[#d8d4ca] bg-white p-6 shadow-[0_14px_36px_rgba(38,48,54,0.05)] sm:p-8"><h2 className="font-display text-2xl font-semibold tracking-[-0.035em]">{title}</h2><div className="mt-4 space-y-4 text-sm leading-7 text-[#59656a]">{children}</div></section>;
}

export function About() {
  return <InfoPage eyebrow="About" title="A practical bridge between music libraries." lead="Universal Backup Merger helps people carry compatible music-library metadata from one app to another without routing their selected backup contents through a conversion server."><Section title="What this site does"><p>The merger inspects compatible backup structures in your browser, identifies a Metrolist target, maps supported music records, validates the output, and offers a download. The dedicated ArchiveTune-to-Bloomee tool creates a portable import handoff for Bloomee.</p><p>The purpose is simple: make migration and backup consolidation more understandable while giving you control over the files you select.</p></Section><Section title="How to use it"><ol className="list-decimal space-y-2 pl-5"><li>Keep an untouched copy of each original backup.</li><li>Choose the conversion or merge workflow that matches your source and destination apps.</li><li>Review detection results, download the generated file, and restore it through the destination app.</li></ol></Section><section className="flex flex-col gap-3 rounded-[26px] bg-[#14212b] p-6 text-white sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display text-2xl font-semibold">Ready to work with a backup?</p><p className="mt-1 text-sm text-[#bdc9cd]">Begin with the browser-based merger.</p></div><a href="/#merge" className="inline-flex items-center justify-center rounded-xl bg-[#f5c77a] px-4 py-3 text-sm font-bold text-[#14212b] hover:bg-[#f9d794]">Start a merge <ArrowRight className="ml-2 size-4" /></a></section></InfoPage>;
}

export function Contact() {
  return <InfoPage eyebrow="Contact" title="Get help without exposing your library." lead="For software questions, bug reports, or feature requests, use the public project issue tracker. Never attach music backups or converted backup files to a public issue."><Section title="What to include"><p>Describe the source app, destination app, app versions, the non-sensitive error text, and the steps that caused it. Screenshots should be reviewed before sharing to ensure that they do not reveal private library details.</p><p>For a privacy-safe report, use filenames only if they contain no personal information. The project team can use this context to improve format support without needing your music data.</p></Section><Section title="Project issue tracker"><a className="inline-flex items-center gap-2 rounded-xl bg-[#b5672c] px-4 py-3 font-bold text-white hover:bg-[#98501f]" href="https://github.com/theneotic/universal-backup-merger-web/issues" target="_blank" rel="noreferrer"><HeartHandshake className="size-4" /> Open a GitHub issue <ExternalLink className="size-4" /></a></Section><div className="flex items-start gap-3 rounded-2xl border border-[#e7d7bd] bg-[#fff9ec] p-4 text-sm leading-6 text-[#76502e]"><Mail className="mt-0.5 size-4 shrink-0" /> This static site does not collect messages through a contact form. The issue tracker is the supported public contact route.</div></InfoPage>;
}

export function Privacy() {
  return <InfoPage eyebrow="Privacy" title="Privacy that starts in your browser." lead="Last updated August 2026. This notice explains what the Universal Backup Merger does with data when you use the public site."><Section title="Backup content"><p>The merger and converter process the backup files you choose in your browser. The application does not upload selected backup contents to a conversion server, and merge history, labels, notes, and generated outputs are stored locally in your browser until you remove them.</p><p>You are responsible for safeguarding original backups and for deleting browser-local history on shared devices.</p></Section><Section title="Site and usage data"><p>The public site may use hosting and privacy-respecting analytics services that receive limited technical information necessary to deliver and measure the site, such as browser, device, page, and network information. This is separate from the music backup files handled by the browser workflow.</p><p>This site does not sell backup contents. It does not provide a public upload gallery or a user account service for the browser-local workflow.</p></Section><Section title="Your choices"><p>You can clear local merge history from the site, clear this site’s browser storage through your browser settings, and avoid submitting sensitive data in public support requests. If you use a third-party host or destination music app, its own privacy terms govern that service.</p></Section></InfoPage>;
}

export function Terms() {
  return <InfoPage eyebrow="Terms" title="Terms for using the backup tools." lead="Last updated August 2026. By using Universal Backup Merger, you agree to use the tools responsibly and to keep independent copies of your original data."><Section title="Your responsibility"><p>You represent that you have the right to process the backups you choose. Before restoring any generated file, keep an untouched copy of every original backup and follow the destination app’s own restore guidance.</p><p>Music applications, their schemas, and backup formats can change without notice. Compatibility results should be reviewed by you before they are relied upon as the only copy of your library.</p></Section><Section title="Service availability"><p>The site is provided on an “as is” and “as available” basis. No warranty is made that every backup format, destination app, or restore result will be supported. The site does not claim affiliation with Metrolist, ArchiveTune, Bloomee, OuterTune, EchoMusic, SimpMusic, RiPlay, or their respective owners.</p></Section><Section title="Acceptable use"><p>Do not use the service to process data you do not have permission to access. Do not attempt to upload malicious files or use the public issue tracker to disclose private libraries, account credentials, or personal information.</p></Section><div className="flex items-start gap-3 rounded-2xl border border-[#cbe2d5] bg-[#eef7f1] p-4 text-sm leading-6 text-[#2f654f]"><ShieldCheck className="mt-0.5 size-4 shrink-0" /> Your original backup remains your best recovery point. Test any restoration carefully and retain your independent copy.</div></InfoPage>;
}
